{
 "title": "Projeto Korp — HTTP Server",
 "description": "Dashboard de monitoramento do http-server-projeto-korp",
 "tags": [
  "korp",
  "devops"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status do Serviço",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_availability_status", "legendFormat": "Status" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "Requisições" }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "req/s (média 1m)" }
   ]
  }
 ]
}